"""Compare Krylov and GCIM-like non-variational UCCSD bases as K increases.

This script builds a six-system comparison using:
- the TrimCI-reduced Hamiltonian as the common projected-space reference
- Krylov states generated inside that reduced space
- two non-variational UCCSD basis families, one ranked by MP2 amplitudes and
  one ranked by CCSD amplitudes, both generated directly in the same retained
  determinant basis

For the UCCSD side, each added basis state is generated by one ranked UCCSD
excitation generator acting on the Hartree-Fock reference at its fixed MP2- or
CCSD-assigned amplitude:
    K = 1 : HF
    K = 2 : HF + top-1 excitation-generator state
    K = 3 : HF + top-2 excitation-generator states
    ...

Outputs:
- Krylov_vs_UCCSD_K_Comparison.csv
- Krylov_vs_UCCSD_K_Comparison.png
- Krylov_vs_UCCSD_K_Comparison.pdf
"""

from __future__ import annotations

import csv
import os
import tempfile
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", os.path.join(tempfile.gettempdir(), "mpl"))

import matplotlib.pyplot as plt
import numpy as np
import pennylane as qml
from scipy.linalg import expm
from pyscf import cc, gto, mp, scf as pyscf_scf

from krylov_grid_search_trimci import (
    DEFAULT_BASIS,
    DEFAULT_S_EVAL_CUTOFF,
    DEFAULT_TRIMCI_NDETS,
    DEFAULT_TRIMCI_NDETS_EXPLORE,
    DEFAULT_TRIMCI_NEXPLORATION,
    SYSTEMS as TRIMCI_SYSTEMS,
    build_reduced_space_context,
    krylov_basis_states,
    run_grid_search_for_system,
    solve_projected_krylov_energy,
)
from uccsd_initializers import restricted_amplitudes_to_theta

SYSTEMS = ("H2", "H4", "LiH", "N2", "C2H4", "C3H8")
SYSTEM_LABELS = {
    "H2": r"H$_2$",
    "H4": r"H$_4$",
    "LiH": "LiH",
    "N2": r"N$_2$",
    "C2H4": r"C$_2$H$_4$",
    "C3H8": r"C$_3$H$_8$",
}
TARGET_K = 20
HEAD_TO_HEAD_DELTA_GRID = np.linspace(0.05, 2.00, 40)
PLOT_FLOOR_MHA = 1.0e-6
CHEMICAL_ACCURACY_MHA = 1.6
COLORS = {
    "krylov": "#1d4e89",
    "mp2_hierarchy": "#2a9d8f",
    "ccsd_hierarchy": "#e76f51",
}
MARKERS = {
    "krylov": "o",
    "mp2_hierarchy": "^",
    "ccsd_hierarchy": "s",
}
LABELS = {
    "krylov": "Krylov",
    "mp2_hierarchy": "MP2",
    "ccsd_hierarchy": "CCSD",
}


def parse_atom_string(atom: str) -> tuple[list[str], np.ndarray]:
    """Parse a PySCF-style atom string into symbols and geometry arrays."""

    symbols: list[str] = []
    geometry: list[list[float]] = []
    for chunk in str(atom).split(";"):
        fields = chunk.split()
        if not fields:
            continue
        symbols.append(str(fields[0]))
        geometry.append([float(fields[1]), float(fields[2]), float(fields[3])])
    return symbols, np.array(geometry, dtype=float)


def build_mp2_ccsd_points_pyscf(
    symbols: list[str],
    geometry: np.ndarray,
    *,
    basis: str,
    unit: str,
) -> tuple[np.ndarray, np.ndarray, list[list[int]], list[list[int]], int]:
    """Build MP2 and CCSD theta vectors with one shared PySCF RHF reference."""

    atom = [[str(sym), tuple(map(float, xyz))] for sym, xyz in zip(symbols, geometry, strict=True)]
    mol = gto.M(atom=atom, basis=str(basis), unit=str(unit), charge=0, spin=0, verbose=0)
    mf = pyscf_scf.RHF(mol).run()

    n_electrons = int(mol.nelectron)
    n_spatial_orbitals = int(mf.mo_coeff.shape[1])
    singles, doubles = qml.qchem.excitations(n_electrons, 2 * n_spatial_orbitals)
    singles = [list(exc) for exc in singles]
    doubles = [list(exc) for exc in doubles]

    mp2_solver = mp.MP2(mf)
    _e_corr_mp2, t2_mp2 = mp2_solver.kernel()
    t1_mp2 = np.zeros((n_electrons // 2, n_spatial_orbitals - n_electrons // 2), dtype=float)
    theta_mp2 = restricted_amplitudes_to_theta(
        singles,
        doubles,
        electrons=n_electrons,
        t1=t1_mp2,
        t2=np.array(t2_mp2, dtype=float),
    )

    ccsd_solver = cc.CCSD(mf)
    _e_corr_ccsd, t1_ccsd, t2_ccsd = ccsd_solver.kernel()
    theta_ccsd = restricted_amplitudes_to_theta(
        singles,
        doubles,
        electrons=n_electrons,
        t1=np.array(t1_ccsd, dtype=float),
        t2=np.array(t2_ccsd, dtype=float),
    )

    return theta_mp2, theta_ccsd, singles, doubles, n_spatial_orbitals


def determinant_pair_to_occupations(alpha_bits: int, beta_bits: int, norb: int) -> np.ndarray:
    """Convert a spatial-orbital determinant pair to interleaved spin occupations."""

    occupations = np.zeros(2 * int(norb), dtype=np.int8)
    for orbital in range(int(norb)):
        occupations[2 * orbital] = 1 if (int(alpha_bits) >> orbital) & 1 else 0
        occupations[2 * orbital + 1] = 1 if (int(beta_bits) >> orbital) & 1 else 0
    return occupations


def occupations_to_pair(occupations: np.ndarray, norb: int) -> tuple[int, int]:
    """Convert interleaved spin occupations back to a determinant pair."""

    alpha_bits = 0
    beta_bits = 0
    for orbital in range(int(norb)):
        if int(occupations[2 * orbital]):
            alpha_bits |= 1 << orbital
        if int(occupations[2 * orbital + 1]):
            beta_bits |= 1 << orbital
    return int(alpha_bits), int(beta_bits)


def apply_annihilation(occupations: np.ndarray, orbital: int) -> tuple[int, np.ndarray] | None:
    """Apply one annihilation operator to an occupation vector."""

    orbital = int(orbital)
    if int(occupations[orbital]) == 0:
        return None
    phase = -1 if int(np.sum(occupations[:orbital])) % 2 else 1
    new_occ = occupations.copy()
    new_occ[orbital] = 0
    return phase, new_occ


def apply_creation(occupations: np.ndarray, orbital: int) -> tuple[int, np.ndarray] | None:
    """Apply one creation operator to an occupation vector."""

    orbital = int(orbital)
    if int(occupations[orbital]) == 1:
        return None
    phase = -1 if int(np.sum(occupations[:orbital])) % 2 else 1
    new_occ = occupations.copy()
    new_occ[orbital] = 1
    return phase, new_occ


def apply_spin_excitation(
    alpha_bits: int,
    beta_bits: int,
    *,
    create: list[int],
    annihilate: list[int],
    norb: int,
) -> tuple[complex, tuple[int, int]] | None:
    """Apply one fermionic excitation operator to a determinant pair."""

    occupations = determinant_pair_to_occupations(alpha_bits, beta_bits, norb)
    coeff = 1
    current = occupations

    for orbital in reversed([int(idx) for idx in annihilate]):
        result = apply_annihilation(current, orbital)
        if result is None:
            return None
        phase, current = result
        coeff *= phase

    for orbital in reversed([int(idx) for idx in create]):
        result = apply_creation(current, orbital)
        if result is None:
            return None
        phase, current = result
        coeff *= phase

    return complex(coeff), occupations_to_pair(current, norb)


def build_excitation_matrix(
    determinant_pairs: list[tuple[int, int]],
    *,
    norb: int,
    excitation: list[int],
) -> np.ndarray:
    """Build one projected fermionic excitation matrix in the TrimCI basis."""

    pair_to_index = {pair: idx for idx, pair in enumerate(determinant_pairs)}
    matrix = np.zeros((len(determinant_pairs), len(determinant_pairs)), dtype=complex)

    if len(excitation) == 2:
        r, p = map(int, excitation)
        create = [p]
        annihilate = [r]
    elif len(excitation) == 4:
        s, r, q, p = map(int, excitation)
        create = [p, q]
        annihilate = [r, s]
    else:
        raise ValueError(f"Unexpected excitation format: {excitation}")

    for col, (alpha_bits, beta_bits) in enumerate(determinant_pairs):
        result = apply_spin_excitation(
            int(alpha_bits),
            int(beta_bits),
            create=create,
            annihilate=annihilate,
            norb=int(norb),
        )
        if result is None:
            continue
        coeff, out_pair = result
        row = pair_to_index.get(out_pair)
        if row is not None:
            matrix[row, col] = coeff

    return matrix


def solve_family_curve(
    basis_states: list[np.ndarray],
    h_det: np.ndarray,
    *,
    max_k: int,
    s_eval_cutoff: float,
    reference_energy: float,
) -> list[dict[str, object]]:
    """Solve projected energies for K = 1, ..., max_k using a fixed ordered family."""

    rows: list[dict[str, object]] = []
    for k_value in range(1, min(int(max_k), len(basis_states)) + 1):
        try:
            energy, min_s_eval = solve_projected_krylov_energy(
                basis_states[:k_value],
                h_det,
                s_eval_cutoff=float(s_eval_cutoff),
            )
        except ValueError:
            break
        rows.append(
            {
                "K": int(k_value),
                "energy_ha": float(energy),
                "gap_to_reference_mha": 1000.0 * (float(energy) - float(reference_energy)),
                "min_overlap_eval": float(min_s_eval),
            }
        )
    return rows


def ranked_operator_indices(theta: np.ndarray, *, max_states: int) -> list[int]:
    """Return the leading excitation indices ranked by amplitude magnitude."""

    theta = np.asarray(theta, dtype=float)
    if theta.ndim != 1:
        raise ValueError("Expected a flat UCCSD amplitude vector.")

    order = np.argsort(-np.abs(theta))
    keep = [int(idx) for idx in order[: max(0, int(max_states))]]
    if keep:
        return keep
    if theta.size == 0:
        raise ValueError("No UCCSD excitations were found for this system.")
    return [int(np.argmax(np.abs(theta)))]


def build_single_generator_state_reduced(
    theta_value: float,
    excitation: list[int],
    reduced,
    *,
    norb: int,
) -> np.ndarray:
    """Build one reduced-space UCC state from a single fermionic generator."""

    excitation_matrix = build_excitation_matrix(
        reduced.determinant_pairs,
        norb=int(norb),
        excitation=[int(idx) for idx in excitation],
    )
    generator = excitation_matrix - excitation_matrix.conj().T

    hf_vec = np.zeros(len(reduced.determinant_pairs), dtype=complex)
    hf_vec[int(reduced.hf_index)] = 1.0
    # PennyLane's excitation-gate convention uses half-angles relative to the
    # bare anti-Hermitian fermionic generator.
    state = expm(0.5 * float(theta_value) * generator) @ hf_vec
    norm = np.linalg.norm(state)
    if not np.isfinite(norm) or np.isclose(norm, 0.0):
        raise ValueError("Generated reduced-space UCC state has invalid norm.")
    return np.asarray(state / norm, dtype=complex)


def build_generator_ranked_family(
    theta: np.ndarray,
    excitations: list[list[int]],
    reduced,
    *,
    norb: int,
    max_k: int,
) -> tuple[list[np.ndarray], list[int]]:
    """Build HF plus ranked single-generator UCCSD states in the reduced space."""

    hf_state = np.zeros(len(reduced.determinant_pairs), dtype=complex)
    hf_state[int(reduced.hf_index)] = 1.0
    states = [hf_state]

    ranked_indices = ranked_operator_indices(theta, max_states=max(0, int(max_k) - 1))
    operator_ranks = [0]

    for operator_index in ranked_indices:
        states.append(
            build_single_generator_state_reduced(
                float(theta[operator_index]),
                excitations[operator_index],
                reduced,
                norb=int(norb),
            )
        )
        operator_ranks.append(int(operator_index) + 1)

    return states, operator_ranks


def build_full_uccsd_state_reduced(
    theta: np.ndarray,
    excitations: list[list[int]],
    reduced,
    *,
    norb: int,
) -> np.ndarray:
    """Build the full one-shot UCCSD state in the reduced determinant space."""

    generator = np.zeros((len(reduced.determinant_pairs), len(reduced.determinant_pairs)), dtype=complex)
    for theta_value, excitation in zip(np.asarray(theta, dtype=float), excitations, strict=True):
        if np.isclose(theta_value, 0.0):
            continue
        excitation_matrix = build_excitation_matrix(
            reduced.determinant_pairs,
            norb=int(norb),
            excitation=[int(idx) for idx in excitation],
        )
        generator += float(theta_value) * (excitation_matrix - excitation_matrix.conj().T)

    hf_vec = np.zeros(len(reduced.determinant_pairs), dtype=complex)
    hf_vec[int(reduced.hf_index)] = 1.0
    state = expm(0.5 * generator) @ hf_vec
    norm = np.linalg.norm(state)
    if not np.isfinite(norm) or np.isclose(norm, 0.0):
        raise ValueError("Generated reduced-space full UCC state has invalid norm.")
    return np.asarray(state / norm, dtype=complex)


def reduced_state_energy(state: np.ndarray, h_det: np.ndarray) -> float:
    """Return the reduced-space expectation value of the Hamiltonian."""

    return float(np.real(np.vdot(state, h_det @ state)))


def find_largest_valid_krylov_target(reduced) -> tuple[int, float]:
    """Find the largest valid Krylov target K up to TARGET_K for one system."""

    k_cap = min(int(TARGET_K), int(len(reduced.determinant_pairs)))
    for candidate_k in range(k_cap, 0, -1):
        try:
            _rows, summary = run_grid_search_for_system(
                reduced,
                delta_grid=np.asarray(HEAD_TO_HEAD_DELTA_GRID, dtype=float),
                k_basis=int(candidate_k),
                s_eval_cutoff=DEFAULT_S_EVAL_CUTOFF,
            )
            return int(candidate_k), float(summary["best_delta_t"])
        except RuntimeError:
            continue
    raise RuntimeError(f"No valid Krylov spacing found for {reduced.label}.")


def collect_system_rows(system: str) -> list[dict[str, object]]:
    """Collect the Krylov/UCCSD comparison rows for one benchmark system."""

    reduced = build_reduced_space_context(
        system,
        basis=DEFAULT_BASIS,
        unit="Angstrom",
        ndets=DEFAULT_TRIMCI_NDETS,
        ndets_explore=DEFAULT_TRIMCI_NDETS_EXPLORE,
        nexploration=DEFAULT_TRIMCI_NEXPLORATION,
        max_keep=None,
    )

    krylov_target_k, best_delta_t = find_largest_valid_krylov_target(reduced)
    krylov_states = krylov_basis_states(reduced, best_delta_t, int(krylov_target_k))
    krylov_rows = solve_family_curve(
        krylov_states,
        reduced.h_det,
        max_k=TARGET_K,
        s_eval_cutoff=DEFAULT_S_EVAL_CUTOFF,
        reference_energy=reduced.reference_energy,
    )

    symbols, geometry = parse_atom_string(TRIMCI_SYSTEMS[system]["atom"])
    theta_mp2, theta_ccsd, singles, doubles, norb = build_mp2_ccsd_points_pyscf(
        symbols,
        geometry,
        basis="sto-3g",
        unit="angstrom",
    )
    excitations = [list(exc) for exc in singles] + [list(exc) for exc in doubles]

    mp2_states, mp2_ranks = build_generator_ranked_family(
        np.asarray(theta_mp2, dtype=float),
        excitations,
        reduced,
        norb=norb,
        max_k=TARGET_K,
    )
    ccsd_states, ccsd_ranks = build_generator_ranked_family(
        np.asarray(theta_ccsd, dtype=float),
        excitations,
        reduced,
        norb=norb,
        max_k=TARGET_K,
    )

    mp2_rows = solve_family_curve(
        mp2_states,
        reduced.h_det,
        max_k=TARGET_K,
        s_eval_cutoff=DEFAULT_S_EVAL_CUTOFF,
        reference_energy=reduced.reference_energy,
    )
    ccsd_rows = solve_family_curve(
        ccsd_states,
        reduced.h_det,
        max_k=TARGET_K,
        s_eval_cutoff=DEFAULT_S_EVAL_CUTOFF,
        reference_energy=reduced.reference_energy,
    )

    mp2_full_state = build_full_uccsd_state_reduced(
        np.asarray(theta_mp2, dtype=float),
        excitations,
        reduced,
        norb=norb,
    )
    ccsd_full_state = build_full_uccsd_state_reduced(
        np.asarray(theta_ccsd, dtype=float),
        excitations,
        reduced,
        norb=norb,
    )
    mp2_full_gap_mha = 1000.0 * (reduced_state_energy(mp2_full_state, reduced.h_det) - float(reduced.reference_energy))
    ccsd_full_gap_mha = 1000.0 * (reduced_state_energy(ccsd_full_state, reduced.h_det) - float(reduced.reference_energy))

    rows: list[dict[str, object]] = []
    for family, family_rows, family_ranks in (
        ("krylov", krylov_rows, [0] + [None] * max(0, len(krylov_rows) - 1)),
        ("mp2_hierarchy", mp2_rows, mp2_ranks),
        ("ccsd_hierarchy", ccsd_rows, ccsd_ranks),
    ):
        for row in family_rows:
            k_value = int(row["K"])
            rows.append(
                {
                    "system": system,
                    "system_label": SYSTEM_LABELS[system],
                    "qubits": int(reduced.qubits),
                    "trimci_determinants": int(len(reduced.determinant_pairs)),
                    "reference_energy_ha": float(reduced.reference_energy),
                    "best_delta_t": float(best_delta_t),
                    "krylov_target_k": int(krylov_target_k),
                    "mp2_full_gap_mha": float(mp2_full_gap_mha),
                    "ccsd_full_gap_mha": float(ccsd_full_gap_mha),
                    "family": family,
                    "K": k_value,
                    "excitation_budget": None if family == "krylov" else int(family_ranks[k_value - 1]),
                    "energy_ha": float(row["energy_ha"]),
                    "gap_to_reference_mha": float(row["gap_to_reference_mha"]),
                    "abs_gap_to_reference_mha": abs(float(row["gap_to_reference_mha"])),
                    "min_overlap_eval": float(row["min_overlap_eval"]),
                }
            )
    return rows


def write_csv(rows: list[dict[str, object]], path: Path) -> None:
    """Write all comparison rows to CSV."""

    fieldnames = [
        "system",
        "system_label",
        "qubits",
        "trimci_determinants",
        "reference_energy_ha",
        "best_delta_t",
        "krylov_target_k",
        "mp2_full_gap_mha",
        "ccsd_full_gap_mha",
        "family",
        "K",
        "excitation_budget",
        "energy_ha",
        "gap_to_reference_mha",
        "abs_gap_to_reference_mha",
        "min_overlap_eval",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def make_plot(rows: list[dict[str, object]], out_png: Path, out_pdf: Path) -> None:
    """Render the six-panel Krylov-vs-UCCSD comparison figure."""

    fig, axes = plt.subplots(2, 3, figsize=(15.6, 8.9), sharex=False, sharey=True, constrained_layout=False)
    fig.subplots_adjust(top=0.94, bottom=0.12, left=0.08, right=0.99, wspace=0.25, hspace=0.36)

    for ax, system in zip(axes.flat, SYSTEMS, strict=True):
        system_rows = [row for row in rows if row["system"] == system]
        mp2_full_gap = max(abs(float(system_rows[0]["mp2_full_gap_mha"])), float(PLOT_FLOOR_MHA))
        ccsd_full_gap = max(abs(float(system_rows[0]["ccsd_full_gap_mha"])), float(PLOT_FLOOR_MHA))
        ax.axhspan(
            float(PLOT_FLOOR_MHA),
            float(CHEMICAL_ACCURACY_MHA),
            facecolor="0.80",
            edgecolor="none",
            alpha=0.80,
            zorder=0,
        )
        ax.axhline(
            float(CHEMICAL_ACCURACY_MHA),
            color="0.35",
            linestyle="--",
            linewidth=1.4,
            alpha=0.95,
            zorder=1,
        )
        for family in ("krylov", "mp2_hierarchy", "ccsd_hierarchy"):
            family_rows = sorted(
                [row for row in system_rows if row["family"] == family],
                key=lambda row: int(row["K"]),
            )
            x = np.array([int(row["K"]) for row in family_rows], dtype=int)
            y = np.array(
                [max(float(row["abs_gap_to_reference_mha"]), float(PLOT_FLOOR_MHA)) for row in family_rows],
                dtype=float,
            )
            ax.plot(
                x,
                y,
                marker=MARKERS[family],
                markersize=5.8,
                linewidth=2.0,
                color=COLORS[family],
                label=LABELS[family],
            )

        ax.axhline(mp2_full_gap, color=COLORS["mp2_hierarchy"], linestyle=":", linewidth=1.8, alpha=0.95)
        ax.axhline(ccsd_full_gap, color=COLORS["ccsd_hierarchy"], linestyle=":", linewidth=1.8, alpha=0.95)

        ax.set_title(SYSTEM_LABELS[system], fontsize=16)
        ax.set_xlabel(r"$K$", fontsize=15)
        k_ticks = [tick for tick in (1, 5, 10, 15, 20) if tick <= max(int(row["K"]) for row in system_rows)]
        if k_ticks:
            ax.set_xticks(k_ticks)
        ax.tick_params(axis="both", labelsize=12, width=1.0, length=4)
        ax.grid(alpha=0.25, which="both")
        ax.set_yscale("log")
        ax.text(
            0.04,
            0.28,
            (
                f"{int(system_rows[0]['qubits'])} qubits\n"
                f"$N_{{\\mathrm{{det}}}}$ = {int(system_rows[0]['trimci_determinants'])}\n"
                f"$K_{{\\mathrm{{Krylov,max}}}}$ = {int(system_rows[0]['krylov_target_k'])}\n"
                f"$\\Delta t^*$ = {float(system_rows[0]['best_delta_t']):.2f}"
            ),
            transform=ax.transAxes,
            ha="left",
            va="bottom",
            fontsize=10.5,
            bbox={"boxstyle": "round,pad=0.24", "facecolor": "white", "alpha": 0.88, "edgecolor": "0.8"},
        )
        ax.legend(
            loc="lower left",
            bbox_to_anchor=(0.02, 0.02),
            fontsize=10.5,
            frameon=True,
            framealpha=0.9,
            facecolor="white",
            edgecolor="0.8",
            borderpad=0.3,
            handlelength=1.8,
        )

    axes[0, 0].set_ylabel(r"$|E_{\mathrm{sub}} - E_{\mathrm{ref}}|$ (mHa)", fontsize=16)
    axes[1, 0].set_ylabel(r"$|E_{\mathrm{sub}} - E_{\mathrm{ref}}|$ (mHa)", fontsize=16)

    fig.savefig(out_png, dpi=220, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    out_dir = Path(__file__).resolve().parent
    rows: list[dict[str, object]] = []
    for system in SYSTEMS:
        rows.extend(collect_system_rows(system))

    write_csv(rows, out_dir / "Krylov_vs_UCCSD_K_Comparison.csv")
    make_plot(
        rows,
        out_dir / "Krylov_vs_UCCSD_K_Comparison.png",
        out_dir / "Krylov_vs_UCCSD_K_Comparison.pdf",
    )

    print(out_dir / "Krylov_vs_UCCSD_K_Comparison.csv")
    print(out_dir / "Krylov_vs_UCCSD_K_Comparison.pdf")


if __name__ == "__main__":
    main()
